### ISSUE TITLE
Support for multiple locale when creating sections

### ISSUE THREAD

**Issue by stevenvandemoortele** [Pennebaker/craftcms-thearchitect#10]
Hi,

Just tried out The architect and loving it so far to quickly set up a cms. Is it possible to add support for multiple locale's when creating a section, or adding to the docs how to do that if it's already possible?

Thanks!

**Comment by spAnser** [comment]
Currently not possible. It just uses the PrimarySiteLocaleId

**Comment by spAnser** [comment]
If you pull from the master repo I just added support for locales.

Check the [Sections](https://github.com/Pennebaker/craftcms-thearchitect/wiki/Sections) Wiki page

**Comment by stevenvandemoortele** [comment]
Awesome! Will check it out tomorrow.
Thanks for the fast reply 👍
