### ISSUE TITLE
Neo Groups get lost 

### ISSUE THREAD

**Issue by sidneywidmer** [Pennebaker/craftcms-thearchitect#12]
I just noticed in the source that the plugin should support the neo plugin? That really would be awesome and it also kind of does, but it loses the "groups" inside a neo field on export. So after importing all fields are just displayed bellow each other.

**Comment by spAnser** [comment]
I haven't looked fully into creating a neo field I can go ahead and create a more in-depth neo field for testing to get the export right.

**Comment by sidneywidmer** [comment]
Thanks for fixing both my issues so quickly!
