### ISSUE TITLE
Feature: import users as models

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craftcms-thearchitect#13]
Frankly, I'm tired of having to add the same couple of core people to the team. We should figure out a way to add users and user groups. Customizing the permissions for the groups would probably be overkill (or would be easier in the system), but perhaps just people.

**Comment by jan-dh** [comment]
This would be great

**Comment by Emkaytoo** [comment]
[This plugin](https://github.com/sjelfull/Craft-UserCreator) shows that you can create users en masse, so it may be worth referencing for this issue.

**Comment by jan-dh** [comment]
I have seen that plugin, but it still forces you to enter all the team-members by hand. We use a kind of boilerplate Craft site with a lot the members, sections, fields,... We just export the sections etc. we need for each new site we make. It speeds up things a lot. Would be nice to have a simple json import of all of our team members that we can just copy/paste in there with it.
