### ISSUE TITLE
Allow Exporting Category Groups

### ISSUE THREAD

**Issue by timknight** [Pennebaker/craftcms-thearchitect#14]
The plugin currently supports exporting Asset Sources. Is exporting Category Groups currently within the roadmap? 

Category Groups can be accessed from

`craft.categoryGroups.getEditableGroups()`

**Comment by spAnser** [comment]
You can import category groups right? This might've been something I forgot when adding export functionality.

**Comment by timknight** [comment]
I don't believe so. I dug into the documentation and didn't see anything for CategoryGroups. I saw within the [Category field type documentation](https://github.com/Pennebaker/craftcms-thearchitect/wiki/Categories) that you can specify the source CategoryGroup but I don't anything on how to export or import them.

**Comment by spAnser** [comment]
It has been a while since I did some updates. I am not seeing that I worked on category groups at all. I can add this in at some point when I get time to work on this again.

**Comment by timknight** [comment]
No problem, I just wanted to make sure it's noted. This has been an incredibly helpful plugin for me. So while I might not be able to contribute plugin development I'm happy to contribute documentation help, ux assistance, or even sharing some of my library that I'm working up.

**Comment by Emkaytoo** [comment]
Glad to hear it's been a help. I'm curious to hear about the library you're building. We haven't really added to the library in a little while. It's not off the board, but just not something we focused on. My goal is to start adding models for some of the blocks we find ourselves using over and over, but I'd love to hear about what kinds of content you find yourself repeating.

**Comment by timknight** [comment]
Yeah, the plugin is huge for me actually. I've been slowly learning more in terms of plugin development and would gladly contribute where possible. In terms of the library for me there are a couple of things I find myself building often that I'm building as Architect JSON files:
1. My basic setup which includes an About single, a Contact Us single, and a standard Asset source (that gets used by other json files by default).
2. A basic blog setup with includes the Blog channel with related fields like category, tags, and body. This is where the CategoryGroup thing comes from.
3. A Testimonials Structure
4. A Staff Bios Structure and Staff Bios Single
5. A FAQs Structure

For each of the corresponding .json files I have default templates that I pull in too that give me some standard output to prototype the functionality. I then use all of this as the basis to design around.
