### ISSUE TITLE
Errors when exporting sections not assigned to primary locale

### ISSUE THREAD

**Issue by steverowling** [Pennebaker/craftcms-thearchitect#23]
The Architect 1.5.2, Craft CMS Pro 2.6.2949

I'm experiencing errors when I'm attempting to export sections that have only been assigned to a locale that is not the primary locale for the site.

Screenshot of error attached.

![screen shot 2016-10-21 at 13 24 31](https://cloud.githubusercontent.com/assets/4478560/19598247/c60cf68e-9791-11e6-8bcb-c59a8de69554.png)

The sections in question don't have URLs and the error is being thrown by the line attempting to set the `nestedUrlFormat` for the section, which appears to always be referencing the primary locale for the site.

Would it make more sense to first check if there is a `urlFormat` set for the section and automatically set the `nestedUrlFormat` to `null` if the section doesn't have URLs?

**Comment by spAnser** [comment]
Looks like sections with locales in general are not being exported properly at all. Have a fix coming in shortly.
