### ISSUE TITLE
Updating Neo Fields (or other)

### ISSUE THREAD

**Issue by 23d1** [Pennebaker/craftcms-thearchitect#26]
I realize this is probably more of a migration issue (for what's slated for 1.6.0), but is there any simple way to modify the input/construct action to update fields by removing/adding/changing names of blocks? 

My current issue having added a block type, but I foresee modifications could become a problem down the line. I suppose this goes for all field types, of course.

**Comment by spAnser** [comment]
I haven't played with neo yet. I was busy this week so the 1.6.0 develop branch is on hold for now. Feel free to download it onto a test install of craft and play with things.

**Comment by 23d1** [comment]
I can wait. When it comes to database migrations and so forth I'm quite useless. ;)

**Comment by 23d1** [comment]
Actually, if the functionality is in the develop branch, it might be worth checking out. Anything I need to uncomment or enable to get migrations working, or it's automatic?

**Comment by spAnser** [comment]
The develop branch should be ready to go for testing there is some minor things I am still working on with it. But Once installed check out the Migrations tab under The Architect in the CP.

**Comment by 23d1** [comment]
Awesome, gonna try it out and report back.

**Comment by 23d1** [comment]
Allright, I realize I reported in the other issue thread.
