### ISSUE TITLE
PHP error when exporting rich text fields

### ISSUE THREAD

**Issue by benjamminf** [Pennebaker/craftcms-thearchitect#27]
I'll preface this issue report with this: [this is actually a result of a Craft bug](https://craftcms.uservoice.com/forums/285224-bugs/suggestions/16896796-rich-text-field-doesn-t-save-checkbox-settings-cor).

So what's happing is a rich text field with no checked asset sources and/or transforms ends up throwing a PHP warning on export.

<img width="998" alt="screen shot 2016-11-01 at 6 46 34 pm" src="https://cloud.githubusercontent.com/assets/6325915/19882684/8ff394ce-a063-11e6-9628-30e361202788.png">

Looking into this, it's due to the fact that Craft is now _always_ storing these "availableAssetSources" and "availableTransforms" keys in the database JSON. This is probably not the right behaviour, but depending on how Craft handle the bug linked above, it may always be the case. I guess the trivial solution would be to add a check for either if the setting is not an empty string, or if the setting is an array.

**Comment by spAnser** [comment]
So running into a weird bug here where when I create a RichText field to try and replicate this problem. I uncheck asset sources & transforms. But when I save the field and go back in to edit it everything is checked again.

**Comment by spAnser** [comment]
Turns out it is saving the field with the values set to unchecked but they appear rechecked when viewing the field.

Went and looked at your bug report that is what you are seeing too.

**Comment by spAnser** [comment]
Should be fixed in v1.5.5
