### ISSUE TITLE
add composer.json file

### ISSUE THREAD

**Issue by diggy** [Pennebaker/craftcms-thearchitect#29]
type: `craft-plugin`

**Comment by spAnser** [comment]
Someone has created a fork of a slightly older version and done this.

https://github.com/onedesign/craftcms-thearchitect/tree/6c075dcaadd520a0f8a6221a55daace60bfcbf32

However is there a way to do this properly without bringing the files to the root?

**Comment by diggy** [comment]
@spAnser I realised the problem a few minutes after I posted this issue :) I'm more of a composer "end user", so I'm not really sure. I'll try to look into it, will let you know if I find something.

**Comment by spAnser** [comment]
I added one let me know if it works at all
