### ISSUE TITLE
Plugin name could provide more context

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craftcms-thearchitect#3]
Lets think of a more descriptive name for the plugin. Generator is a fairly generic term, and if we want people using it, we should provide a little more context for it.

Another thought is to actually name it something out-of-context like Redactor, which is a WYSIWYG editor and there's little if any shared context there.

Spitballing ideas here:
- Content Model Generator
- Model Generator
- CM Factory (factories make things)
- Factory 
- CM Powerplant (plants make things, powerplants connote where the rest of the machine comes from)
- PB Factory (helps people remember Pennebaker, but also we don't make peanut butter)

Seems like a stupid issue to raise, but let's give it some care. Anyone else have thoughts?

**Comment by alexgleason** [comment]
"Craft JSON Models" is very clear.

**Comment by alexgleason** [comment]
Nice
