### ISSUE TITLE
NEO Field Export Failed

### ISSUE THREAD

**Issue by davidhellmann** [Pennebaker/craftcms-thearchitect#30]
Hey, any Idea why the Export crashed? In my Neo Field are some Modules with Super Tables.
![image](https://cloud.githubusercontent.com/assets/764292/21085487/0ad86e7a-c013-11e6-9c39-9f233e17e368.png)

I renamed the Neo field with _ or z in front of the Name to bring it to top or bottom in the Field list. 

Here are a Overview:
![image](https://cloud.githubusercontent.com/assets/764292/21085502/341c655c-c013-11e6-8641-d0742c459010.png)

Cheers

**Comment by spAnser** [comment]
Super Table has been having a lot of updates lately. I will double check it is still correctly compatible with it.

**Comment by davidhellmann** [comment]
Cool, sounds good!

**Comment by spAnser** [comment]
What plugin versions are you using for SuperTable, Neo and The Architect.

**Comment by davidhellmann** [comment]
All Plugins are on the newest Versions.

**Comment by spAnser** [comment]
This bug arose from Importing a super table using Field Manager.

Where the Field Manager did not properly store the width value inside the SuperTable fields. Re-Saving the SuperTables through the CP appears to have fixed this issue.
