### ISSUE TITLE
Neo child blocks

### ISSUE THREAD

**Issue by pl-mnm** [Pennebaker/craftcms-thearchitect#31]
Hi, I'm having issues exporting a Neo field. To be honest I'm not sure if this belongs here or in the Neo issues, but since Neo is working fine otherwise, I'm giving it a shot here:

When I select the field to export, I get: `Property "Craft\Neo_BlockTypeModel.maxChildBlocks" is not defined.`

I tried changing all the blocks number settings, but nothing seems to work. Could this come from the Architect? Thanks in advance.

**Comment by spAnser** [comment]
So maxChildBlocks was added in the newer Neo versions. Try updating Neo. If you have updated Neo try editing and saving every Neo field without change to trigger the maxChildBlocks setting to be saved to the field. That should fix it.

I will leave this open, this error should probably be more graceful anyways.

**Comment by pl-mnm** [comment]
Great, that worked. I thought I had the latest version of Neo but reinstalling it made some changes to the DB.

Thanks!
