### ISSUE TITLE
504 error when constructing field via raw data field v1.6.0-beta.3

### ISSUE THREAD

**Issue by jamesmacwhite** [Pennebaker/craftcms-thearchitect#38]
We recently updated to v1.6.0-beta.3 in a project that uses The Architect plugin, it seems on v1.6.0-beta.3, the raw data field doesn't appear to work correctly. Placing any data in this field and constructing it basically causes a timeout and sits endlessly after posting the request, till eventually a 504 error is thrown.

This happens with any data, doesn't matter if its valid JSON or not.

Downgrading back to the 1.5.5.3 release allows the raw data field to work correctly.

I did enable CRAFT_DEBUG, but I didn't get any meaningful error info.

Any ideas?

**Comment by spAnser** [comment]
It is the rollback attempt.

I am probably going to scrap the feature for now, but it uses the built in craft database backup and rollback when an error occurs. Unfortunately it isn't working properly.

**Comment by jamesmacwhite** [comment]
@spAnser Thanks for the info. That's fine, we'll stick to the latest stable for now. Thanks!

**Comment by spAnser** [comment]
I was really hoping it would work seeing as it wasn't exactly something I created but is used as part of Crafts Auto Updater.

**Comment by jamesmacwhite** [comment]
@spAnser No worries, as its a beta, its no problem. We downgraded back to 1.5.5.3 and its working fine for our needs.
