### ISSUE TITLE
Add support for file selection & upload

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craftcms-thearchitect#4]
I think a useful feature would be to allow for file selection straight from the generator screen, so that a series of separate files can be stored locally and added per project as the user sees fit, and then processed from the uploaded file instead of copy & paste.

For example, a _meta-data.json_ file could be uploaded to create the metadata group, fields, and field layout. This would be useful for projects that have similar fields and groups, but don't need to have the exact same content model all of the time.

**Comment by spAnser** [comment]
Generate from file is added in.
