### ISSUE TITLE
Assets options

### ISSUE THREAD

**Issue by billymedia** [Pennebaker/craftcms-thearchitect#5]
I am trying to create an Assets field, what do i put in the following options:

 "defaultUploadLocationSource": "",
No matter what i put here, it throws an error.

"restrictFiles": true,
How to i specify what to restrict? e.g. images

**Comment by Emkaytoo** [comment]
You can restrict files pretty easily using the "allowedKinds" handle. It takes an array of the types that you would find in the assets field. I've updated the [Assets wiki page](https://github.com/Pennebaker/craftcms-generator/wiki/Assets) to show an example (our bad for leaving it out).

We can look into the "defaultUploadLocationSource" issue.

**Comment by spAnser** [comment]
[Assets wiki page](https://github.com/Pennebaker/craftcms-generator/wiki/Assets) updated. It had some incorrect info related to that part.

```
            "defaultUploadLocationSource": "1", // Asset Source ID change after field creation unless you know it.
            "defaultUploadLocationSubpath": "path/to/subfolder",
```

**Comment by billymedia** [comment]
Perfect, thanks.
