### ISSUE TITLE
Error on import: Undefined property: stdClass::$fieldLayout

### ISSUE THREAD

**Issue by russback** [Pennebaker/craftcms-thearchitect#52]
Looks like the export didn't include a fieldLayout property on the JSON when no fields have been set on the tag element.

```
"tags": [
        {
            "id": "1",
            "name": "Default",
            "handle": "default"
        },
        {
            "id": "2",
            "name": "Sites",
            "handle": "sites"
        }
    ]
```

The error was thrown from `craft/plugins/thearchitect/services/TheArchitectService.php:1743`

**Comment by spAnser** [comment]
I cannot seem to reproduce this using your data.

![](https://i.imgur.com/90bDDTx.png)

**Comment by spAnser** [comment]
After updating my dev environment I am now running into this issue. I am working on a fix now.
