### ISSUE TITLE
When will the Architect restore the balance in Craft 3 !?

### ISSUE THREAD

**Issue by H-i-red** [Pennebaker/craftcms-thearchitect#61]

**Comment by Emkaytoo** [comment]
Hopefully in January.

**Comment by H-i-red** [comment]
# Awesome := )

**Comment by ipatate** [comment]
Hello, compatibility with Craft 3 ?

**Comment by Emkaytoo** [comment]
On the docket! We're getting our Craft 3 workflow and dev environment set up (in progress), then addressing the Architect.

**Comment by ipatate** [comment]
Nice !

**Comment by Emkaytoo** [comment]
<img width="482" alt="Just saying..." src="https://user-images.githubusercontent.com/6294225/35414316-b80f4232-01e7-11e8-817d-858974ccf095.png">

**Comment by spAnser** [comment]
![image](https://user-images.githubusercontent.com/193938/35416241-0fb05be2-01ee-11e8-9a5b-2322fd7879f2.png)
Was told the 3 is a bad idea.

**Comment by spAnser** [comment]
First beta release is out and supports field group and field imports. https://github.com/pennebaker/craft-architect
