### ISSUE TITLE
Exports doesn't work

### ISSUE THREAD

**Issue by davidhellmann** [Pennebaker/craftcms-thearchitect#62]
Get an error when I try to export some Fields, Sections:

TypeError
Argument 1 passed to craft\services\AssetTransforms::getTransformById() must be of the type integer, string given, called in /Users/davidhellmann/___DEV/___Private/craft3/___dist/vendor/pennebaker/craft-architect/src/base/Processor.php on line 236

Some fields work.

**Comment by spAnser** [comment]
Is this for Craft 3 ?

**Comment by spAnser** [comment]
Can you report this on the craft 3 repo. https://github.com/Pennebaker/craft-architect/issues

The problem field is redactor?

**Comment by davidhellmann** [comment]
Ah, sorry. :)
