### ISSUE TITLE
Homepage = true doesn't trigger on import

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craftcms-thearchitect#8]
When designating a section as home page, the checkbox doesn't register in the CMS upon import.

**Comment by spAnser** [comment]
To designate a homepage we need to set

```
 "urlFormat": "__home__",
```

[Sections](https://github.com/Pennebaker/craftcms-thearchitect/wiki/Sections) wiki page has been updated to reflect this info.
